package InterfazGrafica;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;


public class PaginaPrincipal extends javax.swing.JFrame {
    private final Color COLOR_NORMAL       = new Color(0, 0, 102);
    private final Color COLOR_TEXT_NORMAL  = Color.WHITE;
    private final Color COLOR_HOVER        = Color.WHITE;
    private final Color COLOR_TEXT_HOVER   = Color.BLACK;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName());

    AgregarUsuario agregar = new AgregarUsuario();
    BuscarUsuario buscar = new BuscarUsuario();
    ActualizarUsuario actualizar = new ActualizarUsuario();
    EliminarUsuario eliminar = new EliminarUsuario();
    CardLayout vista;
            
    public PaginaPrincipal() { 
        initComponents();
        vista = (CardLayout) vistaPrincipal.getLayout();
        
        btnEliminarUsuario.setBackground(COLOR_NORMAL);
        btnAgregarUsuario.setBackground(COLOR_NORMAL);
        btnBuscarUsuario.setBackground(COLOR_NORMAL);
        btnActualizarUsuario.setBackground(COLOR_NORMAL);

        btnEliminarUsuario.setForeground(COLOR_TEXT_NORMAL);
        btnAgregarUsuario.setForeground(COLOR_TEXT_NORMAL);
        btnBuscarUsuario.setForeground(COLOR_TEXT_NORMAL);
        btnActualizarUsuario.setForeground(COLOR_TEXT_NORMAL);

        addHoverEffect(btnEliminarUsuario);
        addHoverEffect(btnAgregarUsuario);
        addHoverEffect(btnBuscarUsuario);
        addHoverEffect(btnActualizarUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEliminarUsuario = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnBuscarUsuario = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vistaPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnEliminarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.addActionListener(this::btnEliminarUsuarioActionPerformed);
        jPanel1.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 210, 50));

        btnAgregarUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnAgregarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsuario.addActionListener(this::btnAgregarUsuarioActionPerformed);
        jPanel1.add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 50));

        btnBuscarUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnBuscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarUsuario.setText("Buscar Usuario");
        btnBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUsuario.addActionListener(this::btnBuscarUsuarioActionPerformed);
        jPanel1.add(btnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 50));

        btnActualizarUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnActualizarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarUsuario.setText("Actualizar Usuario");
        btnActualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarUsuario.addActionListener(this::btnActualizarUsuarioActionPerformed);
        jPanel1.add(btnActualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_usuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        vistaPrincipal.setBackground(new java.awt.Color(0, 0, 102));
        vistaPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(vistaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 650, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        vistaPrincipal.add(eliminar, "eliminar");
        vista.show(vistaPrincipal, "eliminar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint(); 
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
        vistaPrincipal.add(actualizar, "actualizar");
        vista.show(vistaPrincipal, "actualizar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        vistaPrincipal.add(buscar, "buscar");
        vista.show(vistaPrincipal, "buscar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        vistaPrincipal.add(agregar, "agregar");
        vista.show(vistaPrincipal, "agregar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void addHoverEffect(javax.swing.JButton button) {
        button.setFocusPainted(false);

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                button.setBackground(COLOR_HOVER);
                button.setForeground(COLOR_TEXT_HOVER);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                button.setBackground(COLOR_NORMAL);
                button.setForeground(COLOR_TEXT_NORMAL);
            }
        });
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaginaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel vistaPrincipal;
    // End of variables declaration//GEN-END:variables
}
